### ISSUE TITLE
ExecuteSOQLQuery does not allow output to be stored in Flow variable

### ISSUE THREAD

**Issue by RealEvanPonter** [trailheadapps/automation-components#22]
### Summary

When using the ExecuteSOQLQuery action in a flow, there is no option to store the output value when configuring the action. The action cannot be referenced directly by the flow either.

### Steps To Reproduce:

1.  Install the ExecuteSOQLQuery managed package
1.  Create a new flow
1.  Drag an "Action" element to the canvas
1.  Search for the ExecuteSOQLQuery action
1.  Notice there is only an option to specify the input query. There is no option to specify the object for the SObject "records" output or subsequent flow collection variable selection.

### Expected result

An option to specify the object for the SObject "records" output should appear.

### Actual result

There is only an option to specify the input query

### Additional information

Here is the action configuration screen for the managed package version:
![image](https://user-images.githubusercontent.com/11358831/91582783-48545b00-e91e-11ea-8d49-f84d82dd2d42.png)

I copied the source code from this repository and created a custom class called "ExecuteSOQLQueryCustom". I pasted that code, saved, and tested this version to find that the object for the output can be selected, which then lets you Manually assign variables and save the output in a flow collection of that object.
![image](https://user-images.githubusercontent.com/11358831/91583225-e0eadb00-e91e-11ea-918c-26a3dbfacb3e.png)

I'm thinking that the version of code in the managed package install link might be outdated? Or there is some other consideration for exposing output variables for managed packages?

**Comment by pozil** [comment]
Hi @RealEvanPonter. Thanks for reporting this issue.

The package was up to date but that was a silly mistake on my end: the attribute visibility for the output parameters was set to `public`. This means that it's not accessible in the context of a managed package. I fixed this by changing to to the `global` scope.
Make sure to install the new version of the package to get the updated code.

**Comment by pozil** [comment]
I'm reopening the issue for the time being because I wasn't able to release the package version.
There's an internal bug in the CLI that prevents me from creating a new package version. I'll close the issue when I'm able to update the package.

**Comment by pozil** [comment]
Here's the issue I've opened on the Salesforce CLI project: https://github.com/forcedotcom/cli/issues/594

**Comment by pozil** [comment]
Thanks for your patience @RealEvanPonter. The Salesforce CLI has been updated and I was able to release a new package version with the fix.

**Comment by RealEvanPonter** [comment]
Awesome - thanks so much!
