### ISSUE TITLE
The currently installed version does not share a common ancestor with this version.

### ISSUE THREAD

**Issue by RealEvanPonter** [trailheadapps/automation-components#249]
I'm attempting to upgrade the "AC - Collections" package from v0.1 to v54.1 and I'm seeing this error:
"The currently installed version does not share a common ancestor with this version."

<img width="463" alt="image" src="https://user-images.githubusercontent.com/11358831/193592975-03a5ac98-c3ce-4898-a21e-63a67bac0b53.png">

Is there a method to upgrade this package?

**Comment by pozil** [comment]
Hi @RealEvanPonter, unfortunately this is a problem with older versions of the package. I'm really sorry but I only introduced proper upgrades starting from v50 (Spring '21 on Feb 15 2021). I don't think that there's an easy workaround to this :(
