### ISSUE TITLE
How to specify Output Class in Process Builder

### ISSUE THREAD

**Issue by neilascott** [trailheadapps/automation-components#32]
Hi, 

How do I specify an the field to Output to in the 'Calculate Business Hours' class when called from a Process Builder

I have specified my inputs, but there doesn't appear to be an area for setting which field should be updated

Thanks

![Process-Builder](https://user-images.githubusercontent.com/48760171/93585500-d01e0a00-f99e-11ea-9123-3d1fce174d47.png)

**Comment by pozil** [comment]
Hi @neilascott, thanks for reaching out.
Invocable Actions are shared between Process Builder and Flow Builder.
Unfortunately Process Builder does not support output for actions. This means that you can only use the calculate business hours actions in a Flow.

![Screen Shot 2020-09-19 at 00 21 13](https://user-images.githubusercontent.com/5071767/93650263-57569680-fa0e-11ea-9f7a-bfdb233bfacc.png)

I'm sorry for the confusion but there's - sadly - no way to disable the action in Process Builder.
