### ISSUE TITLE
GACK In Quick Choice CPE

### ISSUE THREAD

**Issue by adwhite75** [trailheadapps/automation-components#336]
### Summary

When setting up a quick choice component and selecting Picklist as the input source, when you click into the Qualified Picklist Field Name (or anywhere in the CPE really), you get a GACK: 

Uncaught TypeError: Cannot read properties of undefined (reading 'apply') throws at https://afloworg.lightning.force.com/auraFW/javascript/MDM0c01pMVUtd244bVVLc2VRYzQ2UWRkdk8xRWxIam5GeGw0LU1mRHRYQ3cyNDYuMTUuNC0zLjAuNA/aura_prod.js:51:43031

### Salesforce Org Type

Production Org

### Steps To Reproduce

Add a Quick Choice component to a screen flow.

Select 'Picklist' as your data source

Click the input/picker for Qualified Picklist Field Name

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Thanks for reporting this @adwhite75, couldn't exactly reproduced the issue but I noticed that there could be some errors when the value of "Qualified Picklist Field Name" doesn't match the expected format. I added some extra validation and a tooltip in the custom property editor.
Can you let me know if this fixes your issue?
