### ISSUE TITLE
Quick Choice does not allow for Record Type Id to be set in the Custom Property Editor

### ISSUE THREAD

**Issue by RealEvanPonter** [trailheadapps/automation-components#73]
### Summary

When implementing a Quick Choice screen component, [the documentation](https://github.com/trailheadapps/automation-components/wiki/ui) suggests that a Record Type Id value can be set in the property editor (it is noted as being a required parameter when Input Source is set to "Picklist"). This is not currently possible.

### Steps To Reproduce:

1. Install the UI package
1. Create a new flow
1. Add a screen to the canvas
1. Add the Quick Choice screen component to the screen
1. Choose the "Picklist" input source
1. Notice there is no Record Type Id property to be specified

### Expected result

There should be a Record Type Id property that accepts a flow resource

### Actual result

There is no Record Type Id property

### Additional information

Here is a screenshot after installing version 50.3 of "AC- UI", adding a quick choice component to a screen, and selecting "picklist" for the Input Source.
![image](https://user-images.githubusercontent.com/11358831/103422791-2b03f780-4b71-11eb-86a0-e4862e2984b6.png)

**Comment by pozil** [comment]
Hi @RealEvanPonter. Tanks for reporting this. That's definitely a bug.
I've released AC- UI v50.4.0 with a fix.
